project:
  type: website
  output-dir: docs

website:
  title: "Awesome hiking blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/RBejder
      - icon: instagram
        href: https://www.instagram.com/rb.venture/
format:
  html:
    theme: darkly
    css: styles.css



