project:
  type: website
  output-dir: docs

website:
  title: "Awesome hiking blog"
  navbar:
    right:
      - index.qmd
      - icon: github
        text: Github
        href: https://github.com/RBejder
        target: "_blank"
      - icon: instagram
        text: Instagram
        href: https://www.instagram.com/rb.venture/
        target: "_blank"
format:
  html:
    theme: darkly
    css: styles.css



