project:
  type: website

website:
  title: "Awesome hiking blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css



